###### PRODUCTS #######

### INDEX
GET http://localhost:3000/products

### SHOW

GET http://localhost:3000/products/9
Content-Type: application/json

### CREATE

POST http://localhost:3000/products
content-type: application/json

{
  "name": "",
  "price": ,
  "image_url": "",
  "description": ""
}

### UPDATE
PATCH http://localhost:3000/products/12
content-type: application/json

{
  "supplier_id": 1
}

### DESTROY

DELETE http://localhost:3000/products/20


##### SUPPLIERS #####

### INDEX
GET http://localhost:3000/suppliers

### SHOW

GET http://localhost:3000/suppliers/9
Content-Type: application/json

### CREATE

POST http://localhost:3000/suppliers
content-type: application/json

{
  "name": "",
  "email": ,
  "phone_number": ""
}

### UPDATE
PATCH http://localhost:3000/suppliers/12
content-type: application/json

{
  "name": ""
}

### DESTROY

DELETE http://localhost:3000/suppliers/3
